# basic options
title: Linux Tutorial - Beginners
author: Brian Bauska
email: brianbauska@gmail.com
description: On-Line Tutorial for Linux Operating System
twitter_username: bbauska
github_username:  bbauska
#
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
#
# Site settings

#baseurl: "/Learn-Linux/" # the subpath of your site, e.g. /blog/
#url: "http://localhost:3000" # the base hostname & protocol for your site

# User settings
#username: bbauska
#user_description: Brian Bauska - don't wear it out
#user_title: This, that and the other
#email: brian.bauska@gmail.com
#twitter_username: bbauska
#github_username:  bbauska
#gplus_username:  bbauska
